# http://www.webdevbreak.com/episodes/zen-textarea-js-finesse/demo

webDevBreak = keyCodes: ESCAPE: 27

webDevBreak.enhanceZenMode = ->
  locationHashPrefix = 'expand_'
  model = activeZenWidget: null

  updateActiveZenWidget = (checkboxForActiveZenWidget) ->
    checkbox = $(checkboxForActiveZenWidget)
    checkbox.prop 'checked', true
    model.activeZenWidget =
      checkbox: checkbox
      textarea: checkbox.parent().find('textarea')
    model.activeZenWidget.textarea.focus()
    window.location.hash = locationHashPrefix + checkbox.prop('id')
    return

  exitZenMode = ->
    if model.activeZenWidget != null
      model.activeZenWidget.checkbox.prop 'checked', false
      model.activeZenWidget = null
      window.location.hash = ''
    return

  watchCheckboxChangesAndUpdateZenMode = ->
    $('body').on 'change', '.zennable input[type=checkbox]', (event) ->
      changedCheckbox = event.currentTarget
      if changedCheckbox.checked
        updateActiveZenWidget changedCheckbox
      else
        exitZenMode()
      return
    return

  watchEscapeKeyAndExitZenMode = ->
    $(document).keydown (event) ->
      if event.keyCode == webDevBreak.keyCodes.ESCAPE
        exitZenMode()
      return
    return

  getCheckboxFromLocationHash = ->
    checkboxId = $.trim(window.location.hash.replace('#' + locationHashPrefix, ''))
    checkbox = null
    if checkboxId
      checkbox = $('.zennable input[type=checkbox]#' + checkboxId)[0]
    checkbox

  watchLocationHashAndUpdateZenMode = ->

    updateZenModeFromLocationHash = ->
      checkbox = getCheckboxFromLocationHash()
      if checkbox
        updateActiveZenWidget checkbox
      else
        exitZenMode()
      return

    $(window).on 'hashchange', updateZenModeFromLocationHash
    return

  watchCheckboxChangesAndUpdateZenMode()
  watchEscapeKeyAndExitZenMode()
  watchLocationHashAndUpdateZenMode()
  return

$(document).ready webDevBreak.enhanceZenMode

# ---
# generated by js2coffee 2.1.0
